export enum ProductType {
    OTATIVO_PERSONAS = 'ROTATIVO_EMPRESAS',
    ROTATIVO_EMPRESAS = 'ROTATIVO_PERSONAS',
    CREDITO_ORDINARIO = 'CREDITO_ORDINARIO',
    CREDITO_FOMENTO = 'CREDITO_FOMENTO',
    SAVINGS = 'SAVINGS',
    CREDIT = 'CREDIT',
    TARJETA_CREDITO = 'TARJETA_CREDITO',
}